# Loading in Residual Count Dataset

- each value shows gene expression via RNA sequencing

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data/RNAseqHarm/ROSMAP_Residualized_counts_(diagnosis-sex-age-death).tsv', delimiter="\t")
df1 = pd.read_csv('data/RNAseqHarm/RNAseq_Harmonization_ROSMAP_combined_metadata.csv')

In [6]:
df.head(10)

feature  510_120515  207_120424  81_120417  649_120529  487_120515  \
0  ENSG00000000003    0.539745   -0.455791   0.029483    0.927509   -0.821087   
1  ENSG00000000419    0.032998   -0.096528  -0.003849    0.177671    0.108173   
2  ENSG00000000457   -0.047954   -0.045705   0.310797    0.065068    0.166983   
3  ENSG00000000460    0.405351    0.317188   0.124757   -0.476037   -0.130254   
4  ENSG00000000938    0.463631    0.351991   0.790630   -0.827755   -0.561926   
5  ENSG00000000971    1.249937   -0.146874   0.441918   -0.236982    0.623419   
6  ENSG00000001036   -0.008286   -0.188718  -0.416688    0.067627   -0.826699   
7  ENSG00000001084   -0.147353   -0.176679  -0.414205    0.319511   -1.245328   
8  ENSG00000001167   -0.072896   -0.090253  -0.412765   -0.063603   -0.390481   
9  ENSG00000001460    0.122713    0.099842  -0.073140    0.338188    0.192039   

   182_120424  193_120424  694_120605  366_120502  ...  RISK_73_redo  \
0   -0.654538   -0.614155    0.214444   -0.128681  ...      0.271698   
1    0.139221    0.224714   -0.057777    0.004272  ...      0.082186   
2    0.095107    0.568559   -0.043476    0.037663  ...     -0.162151   
3   -0.398921   -0.113542   -0.432209    0.244010  ...      0.164703   
4   -0.840376   -0.790768    0.498372    0.877291  ...      1.758510   
5   -1.453353   -0.904159   -0.062802    0.237937  ...      1.266400   
6   -0.316829   -0.273161    0.091899   -0.208860  ...      0.561804   
7   -0.059856   -0.313164    0.383010    0.182327  ...     -0.361973   
8   -0.072175   -0.230172    0.049609   -0.051426  ...      0.191957   
9    0.166705    0.367206   -0.160384    0.151252  ...     -0.615839   

   RISK_74_redo  RISK_78_redo  RISK_8_rerun   RISK_81  RISK_84_redo  \
0      0.589006      0.067369     -0.857244 -0.226842      0.671701   
1     -0.560791      0.040942     -0.284402  0.234696      0.329957   
2     -0.083143      0.167290      0.067710 -0.434691      0.474219   
3      0.168071      0.572947     -0.452513 -0.160455      0.092876   
4      2.478327      1.565875     -0.212365  0.676613      0.769315   
5      1.484600      1.889318     -0.971408  1.495780      1.123114   
6      0.596316      0.589364     -0.899998 -0.399443      0.224895   
7     -0.279739      0.380595     -0.677527 -0.708829      0.328682   
8      0.503687      0.617166     -0.159221  0.087337      0.048982   
9     -0.478519     -0.035306     -0.035690 -0.355101     -0.289961   

   RISK_9_rerun   RISK_93   RISK_94   RISK_97  
0     -0.550307  0.499669  0.351977 -0.035916  
1     -0.052247  0.204763  0.239964  0.327986  
2     -0.189981  0.285131  0.152923  0.158028  
3     -0.273187  0.130140  0.065093 -0.208337  
4     -0.681266 -0.128797 -0.558991 -0.064519  
5     -1.491756 -0.138974 -0.451745 -0.009636  
6     -0.513777  0.036233  0.056219 -0.101588  
7     -0.237025  0.114929  0.071345 -0.145800  
8     -0.421458  0.039707 -0.079274 -0.262131  
9      0.350868 -0.567807 -0.069780 -0.100728  

[10 rows x 2457 columns]

In [7]:
df2 = df.T

In [8]:
df2.head()

0                1                2      \
feature     ENSG00000000003  ENSG00000000419  ENSG00000000457   
510_120515         0.539745         0.032998        -0.047954   
207_120424        -0.455791        -0.096528        -0.045705   
81_120417          0.029483        -0.003849         0.310797   
649_120529         0.927509         0.177671         0.065068   

                      3                4                5      \
feature     ENSG00000000460  ENSG00000000938  ENSG00000000971   
510_120515         0.405351         0.463631         1.249937   
207_120424         0.317188         0.351991        -0.146874   
81_120417          0.124757          0.79063         0.441918   
649_120529        -0.476037        -0.827755        -0.236982   

                      6                7                8      \
feature     ENSG00000001036  ENSG00000001084  ENSG00000001167   
510_120515        -0.008286        -0.147353        -0.072896   
207_120424        -0.188718        -0.176679        -0.090253   
81_120417         -0.416688        -0.414205        -0.412765   
649_120529         0.067627         0.319511        -0.063603   

                      9      ...            18849            18850  \
feature     ENSG00000001460  ...  ENSG00000288030  ENSG00000288033   
510_120515         0.122713  ...         0.023564         -0.97089   
207_120424         0.099842  ...         0.377216         -0.56167   
81_120417          -0.07314  ...        -1.062504         0.379108   
649_120529         0.338188  ...        -0.722717        -0.436119   

                      18851            18852            18853  \
feature     ENSG00000288044  ENSG00000288048  ENSG00000288049   
510_120515        -0.417444        -0.001555        -2.033615   
207_120424        -0.413923         0.312901         2.305215   
81_120417          0.194086        -0.293941         2.348017   
649_120529        -0.636299        -0.038195         -1.59556   

                      18854            18855            18856  \
feature     ENSG00000288061  ENSG00000288062  ENSG00000288075   
510_120515        -0.125635        -0.642736        -0.286241   
207_120424         -0.12738          0.12295        -0.688376   
81_120417          0.746473         -0.17943         0.228797   
649_120529        -0.070071        -0.351987         0.280626   

                      18857            18858  
feature     ENSG00000288107  ENSG00000288108  
510_120515        -0.127179        -0.438888  
207_120424         0.606388          1.22845  
81_120417          0.148467          0.17962  
649_120529        -0.149372         0.555551  

[5 rows x 18859 columns]

In [9]:
df2.reset_index(inplace=True)

In [10]:
df2.columns = df2.iloc[0]
df2 = df2[1:]

In [11]:
df2.rename(columns={'feature':'ID'}, inplace=True)

In [12]:
df2.head()

0          ID ENSG00000000003 ENSG00000000419 ENSG00000000457 ENSG00000000460  \
1  510_120515        0.539745        0.032998       -0.047954        0.405351   
2  207_120424       -0.455791       -0.096528       -0.045705        0.317188   
3   81_120417        0.029483       -0.003849        0.310797        0.124757   
4  649_120529        0.927509        0.177671        0.065068       -0.476037   
5  487_120515       -0.821087        0.108173        0.166983       -0.130254   

0 ENSG00000000938 ENSG00000000971 ENSG00000001036 ENSG00000001084  \
1        0.463631        1.249937       -0.008286       -0.147353   
2        0.351991       -0.146874       -0.188718       -0.176679   
3         0.79063        0.441918       -0.416688       -0.414205   
4       -0.827755       -0.236982        0.067627        0.319511   
5       -0.561926        0.623419       -0.826699       -1.245328   

0 ENSG00000001167  ... ENSG00000288030 ENSG00000288033 ENSG00000288044  \
1       -0.072896  ...        0.023564        -0.97089       -0.417444   
2       -0.090253  ...        0.377216        -0.56167       -0.413923   
3       -0.412765  ...       -1.062504        0.379108        0.194086   
4       -0.063603  ...       -0.722717       -0.436119       -0.636299   
5       -0.390481  ...        0.178033       -0.374037       -0.454228   

0 ENSG00000288048 ENSG00000288049 ENSG00000288061 ENSG00000288062  \
1       -0.001555       -2.033615       -0.125635       -0.642736   
2        0.312901        2.305215        -0.12738         0.12295   
3       -0.293941        2.348017        0.746473        -0.17943   
4       -0.038195        -1.59556       -0.070071       -0.351987   
5        0.559599         3.03256       -0.072668        0.064121   

0 ENSG00000288075 ENSG00000288107 ENSG00000288108  
1       -0.286241       -0.127179       -0.438888  
2       -0.688376        0.606388         1.22845  
3        0.228797        0.148467         0.17962  
4        0.280626       -0.149372        0.555551  
5        0.822951        1.840432        0.002488  

[5 rows x 18860 columns]

In [13]:
df2.shape

(2456, 18860)

In [14]:
df2['ID']

1         510_120515
2         207_120424
3          81_120417
4         649_120529
5         487_120515
            ...     
2452    RISK_84_redo
2453    RISK_9_rerun
2454         RISK_93
2455         RISK_94
2456         RISK_97
Name: ID, Length: 2456, dtype: object

In [78]:
df1['specimenID'].value_counts().head()

88_120417     2
470_120514    2
46_120416     2
460_120514    2
461_120514    2
Name: specimenID, dtype: int64

In [18]:
df1.columns

Index(['specimenID', 'platform', 'RIN', 'libraryBatch', 'sequencingBatch',
       'libraryPrep', 'libraryPreparationMethod', 'isStranded',
       'readStrandOrigin', 'runType', 'readLength', 'notes', 'individualID',
       'organ', 'tissue', 'BrodmannArea', 'nucleicAcidSource', 'isPostMortem',
       'assay', 'exclude', 'excludeReason', 'projid', 'Study', 'msex', 'educ',
       'race', 'spanish', 'apoe_genotype', 'age_at_visit_max',
       'age_first_ad_dx', 'age_death', 'cts_mmse30_first_ad_dx',
       'cts_mmse30_lv', 'pmi', 'braaksc', 'ceradsc', 'cogdx', 'dcfdx_lv'],
      dtype='object')

In [19]:
df3 = df1[['specimenID','cogdx']].copy()
df3['HasAlzheimer'] = df3['cogdx'].apply(lambda x: 1 if x in [4, 5] else 0 if x == 1 else np.nan)

In [20]:
dfx = pd.merge(df3, df2, left_on='specimenID', right_on='ID', how='inner')

In [82]:
dfx['specimenID'].value_counts()

492_120515             1
Sample_R9649089-AC     1
Sample_R5385855-AC     1
Sample_R9254464-AC     1
Sample_R6636386-AC     1
                      ..
Sample_R7944883-PCC    1
Sample_R5225205-AC     1
Sample_R5225205-PCC    1
Sample_R1218460-AC     1
RISK_97                1
Name: specimenID, Length: 1818, dtype: int64

In [22]:
dfx = dfx.drop_duplicates(subset='specimenID')

In [23]:
dfx.shape

(2456, 18863)

In [83]:
dfx['specimenID'].value_counts()

492_120515             1
Sample_R9649089-AC     1
Sample_R5385855-AC     1
Sample_R9254464-AC     1
Sample_R6636386-AC     1
                      ..
Sample_R7944883-PCC    1
Sample_R5225205-AC     1
Sample_R5225205-PCC    1
Sample_R1218460-AC     1
RISK_97                1
Name: specimenID, Length: 1818, dtype: int64

In [86]:
dfx.head()

specimenID  cogdx  HasAlzheimer          ID ENSG00000000003  \
0   492_120515    4.0           1.0  492_120515       -0.432004   
4    02_120405    4.0           1.0   02_120405       -0.816047   
6    03_120405    1.0           0.0   03_120405       -0.958931   
8    04_120405    1.0           0.0   04_120405       -0.115041   
12   07_120410    1.0           0.0   07_120410       -1.026603   

   ENSG00000000419 ENSG00000000457 ENSG00000000460 ENSG00000000938  \
0        -0.062111         0.11296       -0.068069       -0.252136   
4         0.236233        0.276747        0.230103       -0.566289   
6         0.000739        0.548188        0.076068       -0.771854   
8         0.200627        0.227565        0.484526       -0.337223   
12        0.024091       -0.010076       -1.126826        -0.38648   

   ENSG00000000971  ... ENSG00000288030 ENSG00000288033 ENSG00000288044  \
0         -1.14896  ...       -0.048852         -0.0733       -0.161494   
4        -0.964827  ...        1.331595       -0.303728        0.667944   
6        -1.921945  ...        0.283749        0.430266         0.03365   
8        -0.374204  ...       -0.134851        0.174122       -0.195698   
12       -1.162084  ...       -0.063903        0.441658        0.301135   

   ENSG00000288048 ENSG00000288049 ENSG00000288061 ENSG00000288062  \
0        -0.700259        3.569068       -0.337891        0.142195   
4        -1.550739       -1.815264        0.019518        0.368153   
6        -0.445345       -1.337655        0.203595        1.017957   
8        -0.652698       -1.696429        0.320636        -0.06094   
12       -0.254509        3.724301        0.703543        0.581852   

   ENSG00000288075 ENSG00000288107 ENSG00000288108  
0         0.514537        0.088058        0.132191  
4         0.245726       -0.158405       -0.002209  
6         -0.14871        1.903356        0.858265  
8        -0.429307       -0.240233       -0.394856  
12       -0.280216        1.505367       -0.042449  

[5 rows x 18863 columns]

In [26]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   specimenID    3400 non-null   object 
 1   cogdx         3397 non-null   float64
 2   HasAlzheimer  2524 non-null   float64
dtypes: float64(2), object(1)
memory usage: 79.8+ KB


In [27]:
dfx = dfx.dropna()

In [28]:
dfx.shape

(1818, 18863)

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import xgboost as xgb

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [60]:
from keras import models
from keras import layers
from sklearn.utils import class_weight
from sklearn.metrics import confusion_matrix
from keras import regularizers
from keras.layers import BatchNormalization
from keras.layers import Dropout

In [65]:
X = dfx.drop(['specimenID', 'cogdx', 'HasAlzheimer', 'ID'], axis=1)  
y = dfx['HasAlzheimer']
X = X.astype('float32')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [66]:


model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


In [67]:

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.69      0.62      0.65       177
         1.0       0.67      0.73      0.70       187

    accuracy                           0.68       364
   macro avg       0.68      0.68      0.68       364
weighted avg       0.68      0.68      0.68       364

[[110  67]
 [ 50 137]]


In [68]:

model = LogisticRegression(max_iter=1000)


model.fit(X_train, y_train)

y_pred = model.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


Accuracy: 83.52%


In [69]:

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.83      0.84      0.83       177
         1.0       0.84      0.83      0.84       187

    accuracy                           0.84       364
   macro avg       0.84      0.84      0.84       364
weighted avg       0.84      0.84      0.84       364

[[148  29]
 [ 31 156]]


In [70]:

model = xgb.XGBClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 74.18%


In [71]:

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.76      0.69      0.72       177
         1.0       0.73      0.79      0.76       187

    accuracy                           0.74       364
   macro avg       0.74      0.74      0.74       364
weighted avg       0.74      0.74      0.74       364

[[122  55]
 [ 39 148]]


In [72]:
model2 = models.Sequential()

model2.add(layers.Dense(512, activation='relu', input_shape=(18859,)))
model2.add(layers.Dense(256, activation='relu'))
model2.add(BatchNormalization())
model2.add(Dropout(0.5))
model2.add(layers.Dense(128, activation='relu'))
model2.add(BatchNormalization())
model2.add(Dropout(0.5))
model2.add(layers.Dense(1, activation='sigmoid'))




model2.compile(loss='binary_crossentropy',
              optimizer="adam",
              metrics=['acc'])


In [73]:
X_train = X_train.astype('float32')

model2.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2)


Epoch 1/100


2023-07-25 17:25:35.115065: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


37/37 [==============================] - ETA: 0s - loss: 0.8898 - acc: 0.5830

2023-07-25 17:25:36.486396: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


37/37 [==============================] - 2s 33ms/step - loss: 0.8898 - acc: 0.5830 - val_loss: 1.0285 - val_acc: 0.6014
Epoch 2/100
37/37 [==============================] - 1s 14ms/step - loss: 0.7136 - acc: 0.6268 - val_loss: 0.7038 - val_acc: 0.6701
Epoch 3/100
37/37 [==============================] - 0s 13ms/step - loss: 0.6001 - acc: 0.6819 - val_loss: 0.7088 - val_acc: 0.6289
Epoch 4/100
37/37 [==============================] - 1s 14ms/step - loss: 0.5388 - acc: 0.7472 - val_loss: 0.6198 - val_acc: 0.6632
Epoch 5/100
37/37 [==============================] - 0s 13ms/step - loss: 0.4830 - acc: 0.7696 - val_loss: 0.6250 - val_acc: 0.6495
Epoch 6/100
37/37 [==============================] - 1s 14ms/step - loss: 0.3974 - acc: 0.8108 - val_loss: 0.6088 - val_acc: 0.7182
Epoch 7/100
37/37 [==============================] - 0s 13ms/step - loss: 0.3166 - acc: 0.8590 - val_loss: 0.6375 - val_acc: 0.6873
Epoch 8/100
37/37 [==============================] - 0s 13ms/step - loss: 0.2976 - acc: 

Epoch 63/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0555 - acc: 0.9785 - val_loss: 0.9209 - val_acc: 0.7491
Epoch 64/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0420 - acc: 0.9819 - val_loss: 1.0902 - val_acc: 0.7320
Epoch 65/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0312 - acc: 0.9871 - val_loss: 1.1425 - val_acc: 0.7526
Epoch 66/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0530 - acc: 0.9837 - val_loss: 0.9358 - val_acc: 0.7423
Epoch 67/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0373 - acc: 0.9871 - val_loss: 0.8449 - val_acc: 0.7698
Epoch 68/100
37/37 [==============================] - 0s 13ms/step - loss: 0.0373 - acc: 0.9871 - val_loss: 0.9244 - val_acc: 0.7663
Epoch 69/100
37/37 [==============================] - 1s 14ms/step - loss: 0.0353 - acc: 0.9871 - val_loss: 1.1519 - val_acc: 0.7354
Epoch 70/100
37/37 [==============================] - 1s 14ms/step - 

In [75]:
y_pred_proba = model2.predict(X_test)
y_pred = np.where(y_pred_proba > 0.5, 1, 0)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%" % (accuracy * 100.0))


12/12 [==============================] - 0s 7ms/step
Accuracy: 79.40%


In [76]:

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.82      0.74      0.78       177
         1.0       0.77      0.84      0.81       187

    accuracy                           0.79       364
   macro avg       0.80      0.79      0.79       364
weighted avg       0.80      0.79      0.79       364

[[131  46]
 [ 29 158]]
